/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Employee {
  'employeeName' : string,
  'username' : string,
  'password' : string,
}
export interface Payslip {
  'id' : bigint,
  'month' : string,
  'professionTax' : bigint,
  'employeeUsername' : string,
  'employeeName' : string,
  'mobileAllowance' : bigint,
  'ifscCode' : string,
  'incentive' : bigint,
  'dateOfBirth' : string,
  'payableIncentive' : bigint,
  'designation' : string,
  'createdAt' : Time,
  'year' : bigint,
  'businessUnit' : string,
  'payableMobileAllowance' : bigint,
  'bankName' : string,
  'dateOfJoining' : string,
  'insurance' : bigint,
  'employeeId' : string,
  'aadharNumber' : string,
  'paymentMode' : string,
  'accountNumber' : string,
  'panNo' : string,
  'basicSalary' : bigint,
  'payableBasicSalary' : bigint,
  'location' : string,
  'daysPaid' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'username' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPayslip' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
    ],
    undefined
  >,
  'deletePayslip' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPayslip' : ActorMethod<[bigint], Payslip>,
  'getPayslipsByEmployee' : ActorMethod<[string], Array<Payslip>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllEmployees' : ActorMethod<[], Array<Employee>>,
  'listAllPayslips' : ActorMethod<[], Array<Payslip>>,
  'loginAdmin' : ActorMethod<[string], undefined>,
  'loginEmployee' : ActorMethod<[string, string], undefined>,
  'registerEmployee' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePayslip' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];